# =============================================================================
#  Custom rules of Markdown-Lint (Disabled rules)
# =============================================================================

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD013/line-length - Line length
MD013: false

# MD010/no-hard-tabs - Hard tabs
MD010: false
