# =============================================================================
#  Custom rules of Markdown-Lint (Disabled rules)
# =============================================================================

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Number of characters for headings
  heading_line_length: 80
  # Do not check code blocks
  code_blocks: false

# MD010/no-hard-tabs - Hard tabs
MD010: false
